# Generated by Django 4.1 on 2023-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
