# Generated by Django 4.1 on 2023-12-29 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, default='Coming soon...orz', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='nid',
            field=models.CharField(choices=[('国内', 1), ('国际', 2), ('娱乐', 3), ('体育', 4), ('财经', 5), ('科技', 6), ('时尚', 7), ('购物', 8)], max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
