# Generated by Django 4.1 on 2023-12-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content_alter_news_nid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, default='Coming soon...orz', null=True, verbose_name='新闻内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='上传标题图'),
        ),
        migrations.AlterField(
            model_name='news',
            name='nid',
            field=models.CharField(choices=[(1, '国内'), (2, '国际'), (3, '娱乐'), (4, '体育'), (5, '财经'), (6, '科技'), (7, '时尚'), (8, '购物')], max_length=100, verbose_name='新闻类型'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='上传图片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='news',
            name='release_date',
            field=models.DateTimeField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='新闻标题'),
        ),
    ]
