# Generated by Django 5.0 on 2023-12-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content_alter_news_image_alter_news_nid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='buy',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='是否可购买'),
        ),
    ]
