# Generated by Django 5.0 on 2023-12-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='nid',
            field=models.CharField(choices=[('0', '全部'), ('1', '国内'), ('2', '国际'), ('3', '娱乐'), ('4', '体育'), ('5', '财经'), ('6', '科技'), ('7', '时尚'), ('8', '购物')], max_length=100, verbose_name='新闻类型'),
        ),
    ]
