# Generated by Django 5.0 on 2023-12-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operation',
            field=models.CharField(default='0', max_length=255, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_date',
            field=models.DateTimeField(verbose_name='购买日期'),
        ),
    ]
