# Generated by Django 5.0 on 2023-12-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_operation_alter_product_buy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operation',
            field=models.CharField(choices=[('0', '创建'), ('1', '购买')], default='0', max_length=255, verbose_name='操作'),
        ),
    ]
