# Generated by Django 5.0 on 2023-12-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Coming soon...orz', null=True, verbose_name='产品描述'),
        ),
    ]
